import { StyleSheet } from "react-native";

export const ModalStyles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalBodyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalBody: {
    margin: 20,
    backgroundColor: "#e8d6c4",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: "#D4A056",
    width: 300,
  },
  closeButtonContainer: {
    backgroundColor: "#D4A056",
    width: 43,
    height: 43,
    borderRadius: 43 / 2,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.6,
  },
  youOrderText: {
    textAlign: "center",
    color: "#744517",
    fontFamily: "Mont-Bold",
    fontSize: 16,
    marginBottom: 18,
    marginTop: 18,
  },
  totalText: {
    textAlign: "center",
    color: "#744517",
    fontFamily: "Mont-Bold",
    fontSize: 16,
  },
  itemText: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "Mont-Bold",
    fontSize: 16,
  },
  priceText: {
    textAlign: "center",
    color: "#fff",
    fontFamily: "Mont-Bold",
    fontSize: 16,
  },
  doneButtonContainer: {
    backgroundColor: "#fff",
    width: 58,
    height: 58,
    borderRadius: 58 / 2,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.6,
    marginTop: 32,
  },
});
